export const ActionTypes = {
  SET_OPEN_CART: "SET_OPEN_CART",
  SET_ADD_TO_CART_FIRST_TIME: "SET_ADD_TO_CART_FIRST_TIME",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  INCREMENT_ITEM_IN_CART: "INCREMENT_ITEM_IN_CART",
  DECREMENT_ITEM_IN_CART: "DECREMENT_ITEM_IN_CART"
}